const quizData = [
{ en: "a certain", sans: "कश्चन" },
{ en: "according to instruction", sans: "आदेशानुसारं" },
{ en: "after a long time", sans: "बहुकालानन्तरम्" },
{ en: "much, many", sans: "बहु" },
{ en: "time, period", sans: "काल" },
{ en: "after, following", sans: "अनन्तरम्" },
{ en: "again", sans: "पुनः" },
{ en: "all that is happening", sans: "प्रवृत्तं सर्वं" },
{ en: "also", sans: "अपि" },
{ en: "Ambarisha's", sans: "अम्बरीषस्य" },
{ en: "and", sans: "च" },
{ en: "with anger", sans: "कोपेन" },
{ en: "anger, rage, fury", sans: "कोप" },
{ en: "arose", sans: "उत्पन्नः" },
{ en: "arrival", sans: "आगमनतः" },
{ en: "as long as", sans: "यावत्" },
{ en: "at that time", sans: "तत्समये" },
{ en: "because of this", sans: "एतेन" },
{ en: "before that", sans: "ततः पूर्वम्" },
{ en: "before", sans: "पूर्वम्" },
{ en: "best / excellent", sans: "श्रेष्ठः" },
{ en: "by devotion", sans: "भक्त्या" },
{ en: "came", sans: "आगच्छत्" },
{ en: "completed", sans: "समापयन्" },
{ en: "day's", sans: "दिनस्य" },
{ en: "demon", sans: "राक्षसः" },
{ en: "devotee of Vishnu", sans: "विष्णुभक्तः" },
{ en: "discus", sans: "चक्रं" },
{ en: "Durvasa got frightened", sans: "दुर्वासाः भीतः" },
{ en: "afraid, frightened", sans: "भीतः" },
{ en: "even", sans: "अपि" },
{ en: "expressed", sans: "प्रकटीकृतवान्" },
{ en: "fasting vow", sans: "उपवासव्रतं" },
{ en: "fasting", sans: "उपवासम्" },
{ en: "finally", sans: "अन्ते" },
{ en: "for a year", sans: "आवर्षे" },
{ en: "for conclusion", sans: "समापनार्थं" },
{ en: "for eating", sans: "भोजनार्थं" },
{ en: "for his protection", sans: "तदीयरक्षणार्थं" },
{ en: "his, belonging to him", sans: "तदीय" },
{ en: "protection", sans: "रक्षण" },
{ en: "for the sake of, for the purpose of", sans: "अर्थम्" },
{ en: "forgiveness", sans: "क्षमां" },
{ en: "from there", sans: "ततः" },
{ en: "function, duty, task", sans: "कार्यं" },
{ en: "gentle smile", sans: "मन्दहासं" },
{ en: "soft, gentle, slow, mild", sans: "मन्द" },
{ en: "smile, laughter", sans: "हास" },
{ en: "great king", sans: "महाराजः" },
{ en: "great", sans: "महा" },
{ en: "guests", sans: "अतिथयः" },
{ en: "had given", sans: "दत्तवान् आसीत्" },
{ en: "had observed", sans: "आचरितवान्" },
{ en: "to perform, to do", sans: "आचर्" },
{ en: "had returned", sans: "प्रत्यागतवान्" },
{ en: "had sat", sans: "उपविष्टवान्" },
{ en: "having bathed", sans: "स्नात्वा" },
{ en: "having completed", sans: "समाप्य" },
{ en: "having done", sans: "कृत्वा" },
{ en: "having gone", sans: "गत्वा" },
{ en: "having said", sans: "उक्त्वा" },
{ en: "having seen", sans: "दृष्ट्वा" },
{ en: "having slain", sans: "मारयित्वा" },
{ en: "he", sans: "सः" },
{ en: "helpless", sans: "असहायः" },
{ en: "helplessness", sans: "असहायकतां" },
{ en: "holy water", sans: "तीर्थं" },
{ en: "honored", sans: "सत्कृतवान्" },
{ en: "I will return", sans: "आगच्छामि" },
{ en: "I", sans: "अहम्" },
{ en: "in an instant", sans: "अपरक्षणे" },
{ en: "in granting protection", sans: "रक्षणदाने" },
{ en: "in symbolic form", sans: "साङ्केतिकरूपेण" },
{ en: "symbolic", sans: "साङ्केतिक" },
{ en: "in the form of a boon", sans: "वररूपेण" },
{ en: "in the river", sans: "नद्यां" },
{ en: "incapable", sans: "अशक्तः" },
{ en: "insult", sans: "अपमाननम्" },
{ en: "just a moment", sans: "किञ्चित्" },
{ en: "last", sans: "अन्तिम" },
{ en: "may happen", sans: "भवेत्" },
{ en: "may seek", sans: "प्रार्थयतु " },
{ en: "meanwhile", sans: "तावता" },
{ en: "my", sans: "मम" },
{ en: "near Brahma", sans: "ब्रह्मणः समीपं" },
{ en: "near Durvasa", sans: "दुर्वाससः समीपम्" },
{ en: "near Indra", sans: "देवेन्द्रसमीपं" },
{ en: "near Shiva", sans: "शिवसमीपं" },
{ en: "near", sans: "समीपं" },
{ en: "not", sans: "न" },
{ en: "of elders", sans: "गुरूणाम्" },
{ en: "of the fasting vow", sans: "उपवासव्रतस्य" },
{ en: "of the Sudarshana Chakra", sans: "सुदर्शनचक्रस्य" },
{ en: "on the last three days", sans: "अन्तिमदिनत्रये" },
{ en: "once", sans: "कदाचित्" },
{ en: "only", sans: "एव" },
{ en: "passes", sans: "अतीतः" },
{ en: "pleased", sans: "तुष्टः" },
{ en: "ready / attempting", sans: "उध्युत्तः" },
{ en: "refuge", sans: "शरणं" },
{ en: "regarding this", sans: "एतद्विषये" },
{ en: "remembered", sans: "स्मृतवान्" },
{ en: "remembering", sans: "स्मरन्" },
{ en: "running", sans: "धावन्" },
{ en: "sages", sans: "मुनयः" },
{ en: "said", sans: "उक्तवन्तः" },
{ en: "should be concluded", sans: "समापनीयम्" },
{ en: "showing", sans: "प्रकटयन्" },
{ en: "sought", sans: "प्रार्थितवान्" },
{ en: "struck", sans: "ताडितवान्" },
{ en: "Sudarshana Chakra", sans: "सुदर्शनचक्रं" },
{ en: "the auspicious time", sans: "शुभमुहूर्तः" },
{ en: "the ground", sans: "भूमिं" },
{ en: "then", sans: "तदा" },
{ en: "there", sans: "तत्र" },
{ en: "therefore", sans: "अतः" },
{ en: "thus", sans: "इति" },
{ en: "near Ambarisha", sans: "अम्बरीषसमीपं" },
{ en: "to kill", sans: "मारयितुम्" },
{ en: "to stop", sans: "निरोध्दुम्" },
{ en: "to the river", sans: "नदीं" },
{ en: "to Vaikuntha", sans: "वैकुण्ठं" },
{ en: "to Vishnu’s feet", sans: "विष्णुपादौ" },
{ en: "took back", sans: "प्रतिस्वीकृतवान्" },
{ en: "took", sans: "स्वीकृतवान्" },
{ en: "under the control", sans: "अधीनः" },
{ en: "use", sans: "उपयोगः" },
{ en: "Vishnu's discus", sans: "विष्णुचक्रं" },
{ en: "vow's", sans: "व्रतस्य" },
{ en: "vow", sans: "व्रतम्" },
{ en: "wait", sans: "तिष्ठतु" },
{ en: "went", sans: "गतवान्" },
{ en: "when", sans: "यावत्" },
{ en: "with disappointment", sans: "निराशया" },
{ en: "with great", sans: "महता" },
{ en: "with his matted hair", sans: "स्वजटया" },
{ en: "with no other option", sans: "अनन्योपायः" },
{ en: "with respectful hospitality", sans: "आदरातिथ्येन" },
{ en: "respect", sans: "आदर" },
{ en: "hospitality", sans: "अतिथ्य" },
{ en: "worship", sans: "पूजां" },
{ en: "you have committed", sans: "आचरितवान्" },
{ en: "you", sans: "भवान्" },
];
