const quizData = [
{ en: "a fault", sans: "दोषम्" },
{ en: "a great chariot warrior capable of defeating 10,000 soldiers", sans: "महारथः" },
{ en: "a great sin", sans: "महत् पापम्" },
{ en: "a sin", sans: "पातकम्" },
{ en: "Abhimanyu, the son of Subhadra", sans: "सौभद्रः" },
{ en: "about to fight", sans: "योत्स्यमानान्" },
{ en: "according to", sans: "यथा" },
{ en: "adverse / unfavorable", sans: "विपरीतानि" },
{ en: "after seeing", sans: "दृष्ट्वा" },
{ en: "alas", sans: "बत" },
{ en: "all at once", sans: "सहसा" },
{ en: "all", sans: "सर्वे, सर्वान्" },
{ en: "alone", sans: "एव" },
{ en: "also", sans: "च " },
{ en: "although slain", sans: "घ्नतः अपि" },
{ en: "am I able", sans: "शक्नोमि" },
{ en: "among women", sans: "स्त्रीषु" },
{ en: "and all", sans: "सर्वेषाम् च" },
{ en: "and not", sans: "न च" },
{ en: "and", sans: "तथा, च" },
{ en: "are destroyed", sans: "उत्साद्यन्ते, प्रणश्यन्ति" },
{ en: "we", sans: "वयम्" },
{ en: "arises", sans: "जायते" },
{ en: "arranged in military formation", sans: "व्यूढम्" },
{ en: "arranged", sans: "व्यूढाम्" },
{ en: "arrayed (in formation)", sans: "व्यवस्थितान्" },
{ en: "as if", sans: "इव" },
{ en: "as long as", sans: "यावत्" },
{ en: "as well as", sans: "तथा" },
{ en: "assembled / having approached", sans: "समुपस्थितम्" },
{ en: "assembled", sans: "समवेताः, समवेतान्" },
{ en: "battle that has begun", sans: "रण - समुद्यमे" },
{ en: "became", sans: "अभवत्" },
{ en: "because", sans: "यत्" },
{ en: "become corrupted", sans: "प्रदुष्यन्ति" },
{ en: "behold", sans: "पश्य" },
{ en: "being wicked", sans: "दुष्टासु" },
{ en: "betrayal of friends", sans: "मित्र - द्रोहे" },
{ en: "between the two armies", sans: "सेनयोः उभयोः मध्ये" },
{ en: "blew", sans: "प्रदध्मतुः, दध्मुः, दध्मौ" },
{ en: "bow and arrow", sans: "सशरम् चापं" },
{ en: "brothers-in-law", sans: "श्यालाः" },
{ en: "brothers", sans: "भ्रातॄन्" },
{ en: "but", sans: "तु" },
{ en: "by faults", sans: "दोषैः" },
{ en: "by Guḍākeśa (Arjuna)", sans: "गुडाकेशेन" },
{ en: "by kingdom", sans: "राज्येन" },
{ en: "by me", sans: "मया सह" },
{ en: "by the son of Drupada", sans: "द्रुपद - पुत्रेण" },
{ en: "by us", sans: "अस्माभिः, नः" },
{ en: "by your disciple", sans: "तव शिष्येण" },
{ en: "caste mixture", sans: "वर्ण - सङ्करः" },
{ en: "causing joy", sans: "सञ्जनयन् हर्षम्" },
{ en: "certainly", sans: "एव" },
{ en: "comes under unrighteousness", sans: "अधर्मः अभिभवति" },
{ en: "conch named Manipuspaka", sans: "मणिपुष्पकौ" },
{ en: "conch named Sughosa", sans: "सुघोष" },
{ en: "conch shells", sans: "शङ्खाः, शङ्खान्, शङ्खौ" },
{ en: "could we become happy", sans: "सुखिनः स्याम" },
{ en: "desired", sans: "काङ्क्षितम्" },
{ en: "desirous of fighting", sans: "योद्धु - कामान्" },
{ en: "destroyed", sans: "उत्सन्न" },
{ en: "destruction of family", sans: "कुल - क्षय - कृतम्" },
{ en: "Dhristadyumna (the son of King Drupada)", sans: "धृष्टद्युम्नः" },
{ en: "did they do", sans: "अकुर्वत" },
{ en: "divine, transcendental", sans: "दिव्यौ" },
{ en: "division", sans: "भागम्" },
{ en: "do I desire victory", sans: "न काङ्क्षे विजयम्" },
{ en: "do not see", sans: "न पश्यन्ति" },
{ en: "drum", sans: "आनकः" },
{ en: "Drupada, the King of Pancala", sans: "द्रुपदः" },
{ en: "duties", sans: "धर्माः" },
{ en: "eager to fight", sans: "युयुत्सुम्" },
{ en: "equal to Bhīma and Arjuna", sans: "भीम - अर्जुन - समाः" },
{ en: "equipped with weapons", sans: "शस्त्र - प्रहरणाः" },
{ en: "especially powerful", sans: "विशिष्टाः" },
{ en: "eternal", sans: "शाश्वताः" },
{ en: "even", sans: "अपि" },
{ en: "everywhere, on the earth", sans: "सर्वशः पृथिवीपते" },
{ en: "face", sans: "मुखं" },
{ en: "fall", sans: "पतन्ति" },
{ en: "family duties", sans: "कुल - धर्माः" },
{ en: "fathers-in-law", sans: "श्वशुराः, श्वशुरान्" },
{ en: "fathers", sans: "पितरः, पितॄन्" },
{ en: "for hell alone", sans: "नरकाय एव" },
{ en: "for information", sans: "संज्ञार्थं" },
{ en: "for me", sans: "मे" },
{ en: "for my sake", sans: "मदर्थे" },
{ en: "for one’s own people", sans: "स्वजनम् हि" },
{ en: "for the sake of kingdom and pleasure", sans: "राज्य सुख लोभेन" },
{ en: "for the sake of the earth", sans: "महीकृते" },
{ en: "for the sake of", sans: "हेतोः" },
{ en: "for us", sans: "नः" },
{ en: "for whose sake", sans: "येषाम् अर्थे" },
{ en: "friends", sans: "सखीन्, सुहृदः" },
{ en: "from (my) hands", sans: "हस्तात्" },
{ en: "from the rise of unrighteousness", sans: "अधर्म - अभिभवात्" },
{ en: "good", sans: "श्रेयः" },
{ en: "grandsons", sans: "पौत्राः, पौत्रान्" },
{ en: "great chariot warriors", sans: "महारथाः" },
{ en: "great", sans: "महतीम्" },
{ en: "grief-stricken", sans: "शोक" },
{ en: "have taken their positions", sans: "अवस्थिताः" },
{ en: "having abandoned", sans: "त्यक्त्वा" },
{ en: "having approached", sans: "उपसङ्गम्य" },
{ en: "having looked upon", sans: "समीक्ष्य" },
{ en: "having placed", sans: "स्थापयित्वा" },
{ en: "having raised his bow", sans: "धनुः उद्यम्य" },
{ en: "having seen", sans: "दृष्ट्वा" },
{ en: "having slain", sans: "निहत्य, हत्वा" },
{ en: "having uttered", sans: "विनद्य" },
{ en: "he said", sans: "उवाच" },
{ en: "hearts", sans: "हृदयानि" },
{ en: "here", sans: "अत्र" },
{ en: "heroes", sans: "शूराः" },
{ en: "his", sans: "तस्य" },
{ en: "how", sans: "कथम्" },
{ en: "I may look upon", sans: "अवेक्षे अहम्" },
{ en: "I may observe", sans: "निरीक्षे अहम्" },
{ en: "I perceive", sans: "अनुपश्यामि" },
{ en: "I see", sans: "पश्यामि" },
{ en: "I speak", sans: "ब्रवीमि" },
{ en: "I wish", sans: "इच्छामि" },
{ en: "if", sans: "यदि" },
{ en: "immersed", sans: "संविग्न" },
{ en: "in a great chariot", sans: "महति स्यन्दने" },
{ en: "in all", sans: "सर्वेषु" },
{ en: "in battle / when called to fight", sans: "आहवे" },
{ en: "in battle", sans: "युद्धे" },
{ en: "In front of Bhīṣma and Droṇa", sans: "भीष्म - द्रोण - प्रमुखतः" },
{ en: "in great numbers", sans: "बहवः" },
{ en: "in hell", sans: "नरके" },
{ en: "in killing", sans: "हत्वा" },
{ en: "in the battle field", sans: "सङ्ख्ये" },
{ en: "in the place named Kuruksetra", sans: "कुरुक्षेत्रे" },
{ en: "in the place of pilgrimage", sans: "धर्मक्षेत्रे" },
{ en: "in the strategic points", sans: "अयनेषु" },
{ en: "in this", sans: "अस्मिन्" },
{ en: "indeed", sans: "एव च" },
{ en: "indeed", sans: "इमे, तु, हि" },
{ en: "insufficient, immeasurable", sans: "अपर्याप्तम्" },
{ en: "intelligent", sans: "धीमता" },
{ en: "irregular", sans: "अनियतम्" },
{ en: "it is to be fought", sans: "योद्धव्यम्" },
{ en: "just take note of, be informed", sans: "निबोध" },
{ en: "kettledrums", sans: "पणवाः" },
{ en: "kingdom", sans: "राज्यम्" },
{ en: "Kurus", sans: "कुरून्" },
{ en: "large drums", sans: "भेर्यः" },
{ en: "leaders, captains", sans: "नायकाः" },
{ en: "limbs", sans: "गात्राणि" },
{ en: "limited", sans: "पर्याप्तम्" },
{ en: "loudly", sans: "उच्चैः" },
{ en: "Mādhava (Kṛṣṇa)", sans: "माधवः" },
{ en: "many", sans: "नाना" },
{ en: "maternal uncles", sans: "मातुलाः, मातुलान्" },
{ en: "me", sans: "माम्" },
{ en: "mighty bowmen", sans: "महा - इषु - आसाः" },
{ en: "mighty-armed", sans: "महा - बाहुः" },
{ en: "mighty", sans: "विक्रान्तः" },
{ en: "mind", sans: "मानसः, मनः" },
{ en: "mixture", sans: "सङ्करः" },
{ en: "more safe / better", sans: "क्षेमतरम्" },
{ en: "my body", sans: "शरीरे मे" },
{ en: "my own people", sans: "स्वजनम्" },
{ en: "my sons", sans: "मामकाः" },
{ en: "my", sans: "मे, मम" },
{ en: "nor", sans: "न च" },
{ en: "not worthy (it is not right)", sans: "न अर्हाः" },
{ en: "not", sans: "न" },
{ en: "O Acyuta (Kṛṣṇa)", sans: "अच्युत" },
{ en: "O descendant of Vṛṣṇi", sans: "वार्ष्णेय" },
{ en: "O king", sans: "महीपते" },
{ en: "O Pārtha (Arjuna)", sans: "पार्थ" },
{ en: "O Sanjaya", sans: "सञ्जय" },
{ en: "O son of Kunti", sans: "कौन्तेयः" },
{ en: "O teacher", sans: "आचार्य" },
{ en: "occurs / there is", sans: "भवति" },
{ en: "of both armies", sans: "सेनयोः उभयोः" },
{ en: "of destroyers of family", sans: "कुल - घ्नानाम्" },
{ en: "of evil intellect", sans: "दुर्बुद्धेः" },
{ en: "of humans", sans: "मनुष्याणाम्" },
{ en: "of my army", sans: "मम सैन्यस्य" },
{ en: "of the destroyers of family", sans: "कुल - घ्नानाम्" },
{ en: "of the family duties", sans: "कुल - धर्माणाम्" },
{ en: "of the son of Dhṛtarāṣṭra", sans: "धार्तराष्ट्रस्य, धार्तराष्ट्राणाम्" },
{ en: "of the sons of Pāṇḍu", sans: "पाण्डु पुत्राणाम्" },
{ en: "of the three-worlds’", sans: "त्रैलोक्य - राज्यस्य" },
{ en: "of these", sans: "एतेषाम्, एषाम्" },
{ en: "oh", sans: "अहो" },
{ en: "omen/signs", sans: "निमित्तानि" },
{ en: "on seat of the chariot", sans: "रथ - उपस्थे" },
{ en: "one who performs herculean tasks", sans: "भीम - कर्मा" },
{ en: "or by enjoyments", sans: "किम् भोगैः" },
{ en: "or by life itself", sans: "जीवितेन वा" },
{ en: "others", sans: "अन्ये" },
{ en: "otherwise", sans: "उत" },
{ en: "our own people", sans: "स्वजनम्" },
{ en: "our, ours", sans: "अस्माकम्" },
{ en: "overcome with pity", sans: "कृपया परयाविष्टः" },
{ en: "own people", sans: "स्वजनम्" },
{ en: "people desiring to please (him)", sans: "प्रिय-चिकीर्षवः" },
{ en: "place (set)", sans: "स्थापय" },
{ en: "pleasures", sans: "भोगाः, सुखानि" },
{ en: "protect", sans: "अभिरक्षन्तु" },
{ en: "protected by Bhīma (name)", sans: "भीम - अभिरक्षितम्" },
{ en: "relatives", sans: "बन्धून्, सम्बन्धिनः" },
{ en: "releasing", sans: "विसृज्य" },
{ en: "residence", sans: "वासः" },
{ en: "resounding", sans: "अभ्यनुनादयन्" },
{ en: "roaring sound, like that of a lion", sans: "सिंहनादम्" },
{ en: "saw", sans: "अपश्यत्" },
{ en: "separately, one by one", sans: "पृथक् पृथक्" },
{ en: "shivering / hair stands on end", sans: "रोमहर्षः" },
{ en: "should be known", sans: "ज्ञेयम्" },
{ en: "Śikhaṇḍī (name)", sans: "शिखण्डी" },
{ en: "sin only", sans: "पापम् एव" },
{ en: "sinking (in grief)", sans: "विषीदन्" },
{ en: "skilled in military science", sans: "युद्ध - विशारदाः" },
{ en: "sky", sans: "नभः" },
{ en: "slay", sans: "हन्युः" },
{ en: "slips", sans: "स्रंसते" },
{ en: "so", sans: "च" },
{ en: "son of Somadatta", sans: "सौमदत्तिः" },
{ en: "son of Subhadrā", sans: "सौभद्रः" },
{ en: "sons", sans: "पुत्राः, पुत्रान्" },
{ en: "sound", sans: "शब्दः" },
{ en: "spoke", sans: "अब्रवीत्, आह" },
{ en: "standing", sans: "अवस्थितान्, स्थितान्" },
{ en: "strength", sans: "बलम्" },
{ en: "surely", sans: "हि" },
{ en: "teachers", sans: "आचार्याः, आचार्यान्" },
{ en: "that sound", sans: "सः घोषः" },
{ en: "that", sans: "तत्" },
{ en: "the ancestors", sans: "पितरः" },
{ en: "the best of men", sans: "नर पुङ्गवः" },
{ en: "the castes", sans: "जाति" },
{ en: "the chariot", sans: "रथम्" },
{ en: "the conch named Anantavijayam", sans: "अनन्तविजयम्" },
{ en: "the conch named Paundra", sans: "पौण्ड्रम्" },
{ en: "the conch", sans: "शङ्खम्" },
{ en: "the conchshell named Devadatta", sans: "देवदत्तम्" },
{ en: "the conchshell named Pancajanya", sans: "पाञ्चजन्यम्" },
{ en: "the elder of the Kurus", sans: "कुरु - वृद्धः" },
{ en: "the entire family", sans: "कुलम् कृत्स्नम्" },
{ en: "the excellent chariot", sans: "रथ-उत्तमम्" },
{ en: "the Gandīvā bow", sans: "गाण्डीवम्" },
{ en: "the great archer", sans: "परम - इषु - आसः" },
{ en: "the great conch shell", sans: "महा - शङ्खम्" },
{ en: "the King of Kasi", sans: "काश्यः, काशिराजः" },
{ en: "the king", sans: "राजा" },
{ en: "the Pāṇḍava army", sans: "पाण्डव - अनीकम्" },
{ en: "the skin", sans: "त्वक्" },
{ en: "the son of Kuntī", sans: "कुन्ती - पुत्रः" },
{ en: "the son of Pāṇḍu (Arjuna)", sans: "पाण्डवः" },
{ en: "the sons of Dhṛtarāṣṭra", sans: "धार्तराष्ट्राः, धार्तराष्ट्रान्" },
{ en: "the sons of Draupadī", sans: "द्रौपदेयाः" },
{ en: "the sons of Pandu", sans: "पाण्डवाः" },
{ en: "the surface of the earth", sans: "पृथिवीम्" },
{ en: "the teacher", sans: "आचार्यम्" },
{ en: "the valiant one", sans: "प्रतापवान्" },
{ en: "the voracious eater (Bhima)", sans: "वृक - उदरः" },
{ en: "their lives", sans: "प्राणान्" },
{ en: "them", sans: "एतान्, तान्" },
{ en: "then, thereafter", sans: "ततः" },
{ en: "then", sans: "अथ, तदा" },
{ en: "there", sans: "तत्र" },
{ en: "Therefore", sans: "तस्मात्" },
{ en: "these aggressors", sans: "एतान् आततायिनः" },
{ en: "these words", sans: "इदम् वाक्यम्" },
{ en: "these", sans: "एतान्, एते, एतैः" },
{ en: "this", sans: "इदम्, इमम्" },
{ en: "those", sans: "ते" },
{ en: "thus having spoken", sans: "एवम् उक्त्वा" },
{ en: "thus spoken to", sans: "एवम् उक्तः" },
{ en: "thus", sans: "इति" },
{ en: "to be turned away", sans: "निवर्तितुम्" },
{ en: "to commit", sans: "कर्तुम्" },
{ en: "to Hṛṣīkeśa (Kṛṣṇa)", sans: "हृषीकेशम्" },
{ en: "to kill", sans: "हन्तुम्" },
{ en: "to stand", sans: "अवस्थातुम्" },
{ en: "to you", sans: "ते" },
{ en: "tremble", sans: "सीदन्ति" },
{ en: "trembles", sans: "वेपथुः" },
{ en: "tumultuous", sans: "तुमुलः" },
{ en: "unarmed", sans: "अशस्त्रम्" },
{ en: "unconquered", sans: "अपराजितः" },
{ en: "Virata (prince who gave shelter to Pandavas while they were in disguise)", sans: "विराटः" },
{ en: "wanders", sans: "भ्रमति" },
{ en: "we are eager / ready", sans: "उद्यताः" },
{ en: "we have heard", sans: "अनुशुश्रुम" },
{ en: "we have perceived", sans: "प्रपश्यद्भिः" },
{ en: "wealth", sans: "धनानि" },
{ en: "were simultaneously sounded", sans: "अभ्यहन्यन्त" },
{ en: "what indeed", sans: "किम् नु" },
{ en: "what pleasure", sans: "का प्रीतिः" },
{ en: "what", sans: "किम्" },
{ en: "when battle was about to begin", sans: "प्रवृत्ते शस्त्र - सम्पाते" },
{ en: "when dharma is destroyed", sans: "धर्मे नष्टे" },
{ en: "when the family is destroyed", sans: "कुल - क्षये" },
{ en: "who", sans: "ये" },
{ en: "whose funeral rites and offerings", sans: "लुप्त - पिण्ड - उदक - क्रियाः" },
{ en: "with white horses", sans: "श्वेतैः हयैः" },
{ en: "with whom", sans: "कैः" },
{ en: "without resistance", sans: "अप्रतीकारम्" },
{ en: "words", sans: "वचनम्" },
{ en: "would be", sans: "भवेत्" },
{ en: "would cling to us", sans: "आश्रयेत् अस्मान्" },
{ en: "would there be", sans: "स्यात्" },
{ en: "yoked", sans: "युक्ते" },
{ en: "you (warriors)", sans: "भवन्तः, भवान्" },
];
